{% set name = "hydrodata" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f3aa5bec0f550091ac14348f4db437bb3d8c5d764e56d47f018a2922f77bec6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - matplotlib-base
    - lxml
    - folium
    - py3dep
    - pydaymet
    - pygeoogc
    - pygeoutils
    - pynhd

test:
  imports:
    - hydrodata

about:
  home: https://github.com/cheginit/hydrodata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A portal to access hydrology and climatology data

  description: |
    Hydrodata is a python library designed to aid in watershed analysis.
    It provides easy and consistent access to a handful of hydrology and
    climatology databases with some helper functions for visualization.
  doc_url: https://hydrodata.readthedocs.io
  dev_url: https://github.com/cheginit/hydrodata

extra:
  recipe-maintainers:
    - cheginit
